// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic type structure
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
        }
        Insert: {
          id: string
          email: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
        }
      }
      profile: {
        Row: {
          user_id: string
          long_term_goal: string | null
          values_json: Json | null
          strengths_json: Json | null
          redaction_map_encrypted: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          long_term_goal?: string | null
          values_json?: Json | null
          strengths_json?: Json | null
          redaction_map_encrypted?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          long_term_goal?: string | null
          values_json?: Json | null
          strengths_json?: Json | null
          redaction_map_encrypted?: string | null
          updated_at?: string
        }
      }
      docs: {
        Row: {
          id: string
          user_id: string
          type: string
          storage_path: string
          meta_encrypted: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          storage_path: string
          meta_encrypted?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          storage_path?: string
          meta_encrypted?: string | null
        }
      }
      embeddings: {
        Row: {
          id: string
          doc_id: string
          chunk_redacted: string
          vector: number[]
          metadata_json: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          doc_id: string
          chunk_redacted: string
          vector: number[]
          metadata_json?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          doc_id?: string
          chunk_redacted?: string
          vector?: number[]
          metadata_json?: Json | null
        }
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          title: string
          active_goal: string | null
          active_values_json: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          active_goal?: string | null
          active_values_json?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          active_goal?: string | null
          active_values_json?: Json | null
        }
      }
      messages: {
        Row: {
          id: string
          session_id: string
          role: string
          content_redacted: string
          content_encrypted: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          role: string
          content_redacted: string
          content_encrypted?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          role?: string
          content_redacted?: string
          content_encrypted?: string | null
        }
      }
      letters: {
        Row: {
          id: string
          user_id: string
          job_meta_json: Json | null
          draft_html: string
          draft_txt: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          job_meta_json?: Json | null
          draft_html: string
          draft_txt: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          job_meta_json?: Json | null
          draft_html?: string
          draft_txt?: string
        }
      }
      cv_versions: {
        Row: {
          id: string
          user_id: string
          base_doc_id: string
          job_meta_json: Json | null
          diff_summary: string | null
          file_paths_json: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          base_doc_id: string
          job_meta_json?: Json | null
          diff_summary?: string | null
          file_paths_json?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          base_doc_id?: string
          job_meta_json?: Json | null
          diff_summary?: string | null
          file_paths_json?: Json | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
